config/routes.rb
Rails.application.routes.draw do

  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  devise_for :users

  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  get "/carrito", to: "shopping_carts#show"
  delete "/carrito", to: "in_shopping_carts#destroy"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create" 
  get "/checkout", to: "payments#checkout"

  get "/descargar/:id", to:"links#download"
  get "/descargar/:id/archivo/:attachment_id", to:"links#download_attachment",as: :download_attachment
  get "/invalid", to: "welcome#unregistered"

  get "/ok", to: "welcome#payment_succed"

  get "/ordenes", to: "ordenes#index"
  
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @orders = current_user.orders.order("created_at desc")
  end

  def unregistered
  	render layout: "landing"
  end

  def payment_succed
  	if @shopping_cart.payed?
  		cookies[:shopping_cart_id] = nil
  	else
  		redirect_to carrito_path
  	end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.haml
.col-xs-12.col-md-11.center-block.no-float
	.card.large-padding
		.top-space
			.col-md-3.col-xs-12.inline-block.no-padding.in-top
				.text-center
					=link_to "Crear producto",new_product_path, class:"btn btn-info"
				=render current_user.products
			.col-md-9.col-xs-12.inline-block
				=render "payments/index"

app/views/welcome/payment_succed.haml
.col-md-10.center-block.no-float
	%article.card.large-padding
		%h1 Tu pago ha sido procesado
		%p Hemos enviado a tu correo los links de descarga del producto que acabas de adquirir
		%section.big-top-space
			%h2 Resumen de tu pedido
			%table.table.table-striped.table-hover.medium#table_shopping_cart
				%thead
					%td Producto
					%td Costo
				%tbody
					-@shopping_cart.in_shopping_carts.each do |i_sh|
						-product = i_sh.product
						%tr{id: "#{product.id}"}
							%td= product.name
							%td= product.pricing

app/views/welcome/unregistered.haml
%header.green.big-padding
	.col-md-10.no-float.center-block
		.col-md-6.no-padding.inline-block
			=image_tag "tiendus.png",width:"100"
			%h1.white-text.ultra-big.kostic
				%strong
					Ofrece tus productos digitales a tu audiencia
		.col-md-5.inline-block
			=image_tag "mono.png"
.grey.white-text.big-padding.kostic
	
	.col-md-10.no-float.center-block
		.absolute{style:"bottom:-4.5em;width:100%;left:0px;"}
			.text-center.big
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 1
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 2
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 3
		%h2.bigger.kostic.text-center
			%strong Tiendus en 3 pasos
		%div.text-center.top-space
			.col-md-3.inline-block.text-left
				=image_tag "upload-icon.png", class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Sube tus archivos a Tiendus
					%p.white-text.text-justify.small
						¡Libro digital, canción, comic, curso
						o lo que se te ocurra! Si lo puedes
						meter un .Zip, lo puedes vender.* 
			.col-md-3.inline-block.text-left
				=image_tag "youtube-icon.png", class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Cuéntale a tus fans
					%p.white-text.text-justify.small
						Comparte el link personalizado de
						tu producto en tus redes sociales
						o sitio web. 
			.col-md-3.inline-block.text-left
				=image_tag "money-icon.png", class:"col-md-10 inline-block"
				.top-space
					%strong.medium
						Vende y gana dinero
					%p.white-text.text-justify.small
						Recibe tu dinero en tu cuenta de PayPal
						y tu cliente su producto en su email
						inmediatamente. Así de fácil.
.red.white-text.big-padding.kostic{style:"margin-top:5em;"}
	.col-md-8.no-float.text-center.center-block
		=image_tag "media-icons.png"
		%p.medium.col-md-11.center-block.no-float.top-space
			%strong
				Vende tus libros electrónicos, tutoriales, canciones, comics, plantillas, fotografías de stock, archivos fuente, ¡cualquier producto digital!	
.top-space.big-padding.bottom-space
	.col-md-11.col-xs-12.center-block.no-float
		=form_tag(create_email_path,method: :post,remote:true,id: "emails-form") do
			=email_field_tag "email",nil,class:"col-xs-12 inline-block text-center landing-form",placeholder:"Escribe aquí tu mail"
		#email-info.red.white-text.large-padding