config/routes.rb
Rails.application.routes.draw do

  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  devise_for :users

  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  get "/carrito", to: "shopping_carts#show"
  delete "/carrito", to: "in_shopping_carts#destroy"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create" 
  get "/checkout", to: "payments#checkout"

  get "/descargar/:id", to:"links#download"
  get "/descargar/:id/archivo/:attachment_id", to:"links#download_attachment",as: :download_attachment
  get "/invalid", to: "welcome#unregistered"

  get "/ok", to: "welcome#payment_succed"

  get "/ordenes", to: "ordenes#index"
  
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  pricing             :integer
#  description         :text
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :user
  has_many :attachments
  has_many :in_shopping_carts
  has_one :shopping_cart, through: :in_shopping_carts
  has_many :my_payments, through: :shopping_cart

  validates_presence_of :name,:user,:pricing
  validates :pricing, numericality: { greater_than: 0 }

  has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100" },default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def paypal_form
  	{name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:1 }
  end

  def sales
  	my_payments.payed
  end

  def sales_total
  	my_payments.payed.count * self.pricing
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index,:show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if user_signed_in? && current_user == @product.user && !params.has_key?(:client)
      @attachment = Attachment.new
      render :admin
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :pricing, :description,:avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product,builder: BootstrapFormBuilder do |f|
  = f.errors
  = f.text_field :name
  %small Precio en centavos de dólar
  = f.text_field :pricing
  = f.file_field :avatar
  = f.text_area :description
  =f.submit "Enviar"
  

app/views/products/_product.haml
%article
	%h3.large-padding.red.white-text.no-margin= link_to product.name,product,class:"white-text"
	.large-padding.text-left
		.col-md-9.inline-block.no-padding= product.description
		.col-md-3.inline-block.no-padding
			=product.sales.count
			ventas

app/views/products/admin.haml
.col-md-3.no-padding.inline-block.in-top
	%nav.medium
		.white-text.green.col-md-12
			Admin general
.col-md-9.inline-block.in-top
	.card.large-padding
		.col-md-9.inline-block
			%h1= @product.name
		.col-md-3.inline-block
			%p.big.no-margin.red-text
				=@product.sales_total / 100
				USD
		%nav.top-space
			=link_to product_path(id: @product.id,client:true), class:"other-grey large-padding text-center col-md-4 inline-block" do
				Ver como cliente
			=link_to edit_product_path(@product), class:"other-grey large-padding text-center col-md-4 inline-block" do
				Editar producto
			=link_to @product,method: :delete, class:"other-grey large-padding text-center col-md-4 inline-block",:"data-confirm" => "¿Estás seguro de eliminar el producto?" do
				Eliminar producto
		%div
			%h3.grey-text Archivos
			%ol
				-@product.attachments.each do |attachment|
					%li.large-padding.medium.grey-text.other-grey
						.col-xs-11.inline-block= link_to attachment.archivo_file_name, attachment
						.col-xs-1.inline-block
							=link_to attachment, method: :delete,:"data-confirm" => "¿Estás seguro de eliminar el archivo?",class:"red-text" do
								X
			= render "attachments/form", product_id: @product.id

app/views/products/edit.html.haml
.col-md-10.col-xs-12.col-sm-11.no-float.center-block
	.card.large-padding
		%h1 Editar producto
		= render 'form'

app/views/products/index.html.haml
%h1 Listing products

%table
  %thead
    %tr
      %th Name
      %th Pricing
      %th Description
      %th User
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= product.pricing
        %td= product.description
        %td= product.user
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
.col-md-10.col-xs-12.col-sm-11.no-float.center-block
	.card.large-padding
		%h1 Agregar producto
		= render 'form'

app/views/products/show.html.haml
.col-lg-7.col-md-8.col-xs-12.col-sm-10.col-sm-11.no-float.center-block
	%article.card.big-padding
		%header
			%h1.grey-text.bold= @product.name
		%section
			.col-xs-6.col-md-5.no-padding.inline-block
				=image_tag @product.avatar.url
			.col-md-1.inline-block.hidden-xs
			.col-xs-5.col-md-6.inline-block.text-left
				%h3.blue-text.bold.normal= @product.user.email
				%h3.green-text.bold.normal
					Precio:
					%span.grey-text= "$#{@product.pricing}"
				%h3.green-text.bold.normal
					Archivos:
					%span.grey-text 20
				%h3.green-text.bold.normal
					Tamaño:
					%span.grey-text= "2gb"
				=render "in_shopping_carts/form",product: @product
		%section
			%h3.green-text.bold.normal Descripción
			%p= @product.description